name: Check Build Possibility

on:
  pull_request:
    branches: ["main"]

jobs:
  # Build 명령어를 활용한 테스트 진행
  build-test:
    runs-on: ubuntu-20.04
    env:
      DISABLE_ESLINT_PLUGIN: true
    steps:
      - uses: actions/checkout@v3 # feature 브랜치의 코드 가져오기
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "21.2.0"
      - name: Install dependencies
        run: npm install
      - name: Try build
        run: npm run build
